# Generated by Django 5.2 on 2025-04-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_created_at_user_has_completed_tutorial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
