# Generated by Django 5.2 on 2025-07-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_passwordresetcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bot_enabled",
            field=models.BooleanField(
                default=True, help_text="Activer ou désactiver le bot pour ce vendeur"
            ),
        ),
    ]
