# Generated by Django 5.2 on 2025-07-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_bot_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetcode",
            name="code",
            field=models.CharField(max_length=8),
        ),
    ]
