# Generated by Django 5.2 on 2025-07-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_passwordresetcode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="whatsapp_number",
            field=models.CharField(default=22500000000, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
