# Generated by Django 5.2 on 2025-07-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_user_whatsapp_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
