# Generated by Django 5.2 on 2025-04-21 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="messagetemplate",
            index=models.Index(
                fields=["auto_trigger"], name="bot_message_auto_tr_c3983d_idx"
            ),
        ),
    ]
