# Generated by Django 5.2 on 2025-05-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_messagetemplate_bot_message_auto_tr_c3983d_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="botmessagehistory",
            name="confidence_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="botmessagehistory",
            name="detected_intent",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
