# Generated by Django 5.2 on 2025-06-16 11:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_botmessagehistory_confidence_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="colors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
