# Generated by Django 5.2 on 2025-07-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0004_product_colors_product_sizes"),
    ]

    operations = [
        migrations.AddField(
            model_name="botsession",
            name="bot_silence_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
