# Generated by Django 5.2 on 2025-07-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0005_botsession_bot_silence_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
