# Generated by Django 5.2 on 2025-07-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0006_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deposit_number",
            field=models.CharField(
                blank=True,
                help_text="Numéro de dépôt Mobile Money",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="payment_link",
            field=models.URLField(blank=True, help_text="Lien de paiement", null=True),
        ),
    ]
